### ISSUE TITLE
Gradient on back color

### ISSUE THREAD

**Issue by dekadevelop** [kushalmahapatro/cuberto_bottom_bar#10]
Hi would it be possible to insert gradients on the background Color?
Thank you

**Comment by kushalmahapatro** [comment]
Hey @dekadevelop  
Sure, will implement it and let you know. 👍

**Comment by kushalmahapatro** [comment]
hey, @dekadevelop  have added a property in TabData names tabGradient, it can be used to set the gradient to the selected tab. You can have a look and let me know if the requirement is met or have to do some more changes.  :) 

use can use the version 1.1.1+2
