### ISSUE TITLE
Unable to use Highlighter_Coachmark on Cuberto_Bottom_Bar as there is no way to assign a GlobalObjectKey to the Tab in Cuberto_Bottom_Bar.

### ISSUE THREAD

**Issue by infonotics** [kushalmahapatro/cuberto_bottom_bar#13]
I am using Highlighter_Coachmark for directing user on the screen. Highlighter_Coachmark requires a GlobalObjectKey assigned to the widget on which the coach mark is to displayed. As there is no way to assign a GlobalObjectKey to the 'Tabs' object which Cuberto_Bottom_Bar takes, I am unable to use coach marks. Please provide a way to assign GlobalObjectKey to the Tabs. 
Also, thanks for developing this beautiful bottom navigator. Its supercool.

**Comment by kushalmahapatro** [comment]
Hi @infonotics 

Thank you for using this plugin :) 
Will update the code and let you know.

**Comment by kushalmahapatro** [comment]
Hi @infonotics 
Have added the Key that can be assigned to a Tab in version 1.1.2+3, please have a look and let me know if it solves the problem or not? :)
