### ISSUE TITLE
Add key parameter to tabs

### ISSUE THREAD

**Issue by Zazo032** [kushalmahapatro/cuberto_bottom_bar#14]
We are using this plugin in our app, and we need to pass a `key` parameter to each different tab in order to create some integration tests using `test_driver`.

**Comment by Zazo032** [comment]
cc @kushalmahapatro

**Comment by kushalmahapatro** [comment]
Hi @Zazo032 

Sure will add an option to pass key to tabs.

**Comment by kushalmahapatro** [comment]
Hi @Zazo032  

Have added the key in version 1.1.2+3, please have a look and let me know if it solves the problem or not? :)

**Comment by Zazo032** [comment]
I'm going OOF for a few days, will try to test it when I'm back. I'll close for now since changes look good. Thanks!

https://github.com/kushalmahapatro/cuberto_bottom_bar/blob/431918702621104cd36c712f82dfcd90ac5f1fc6/lib/cuberto_bottom_bar.dart#L320

This could be simpler by changing it to:

```dart
  this.key,
}) {
  key ??= UniqueKey();
}
```
