### ISSUE TITLE
Button padding

### ISSUE THREAD

**Issue by erperejildo** [kushalmahapatro/cuberto_bottom_bar#2]
This is more like an improvement than an actual issue. The buttons seems to have some padding around it:
![Captura](https://user-images.githubusercontent.com/5629919/64867805-6312be80-d63e-11e9-9455-cf4f52ec4e03.PNG)

The problem is that we can only click on the actual button, not the whole area and this makes the button more difficult to tap. Could we add this tap event to the container?

**Comment by kushalmahapatro** [comment]
Hi @erperejildo, 
First of all thanks for using cuberto_bottom_bar. 
Yes i have figured out what you have mentioned and have made the respective changes. 
Will provide and update by the end of day or tomorrow. 

Do let me know, if you have any more idea on improvising this plugin. :D 

Thanks.
Kushal

**Comment by kushalmahapatro** [comment]
Hi @erperejildo 
Have updated the plugin with increased button padding. :D

**Comment by erperejildo** [comment]
Sorry for the late response.
I updated it but got this error:
```
The getter 'NO_DRAWER' isn't defined for the class 'CubertoDrawer'.
Try importing the library that defines 'NO_DRAWER', correcting the name to the name of an existing getter, or defining a getter or field named 'NO_DRAWER'.
```

**Comment by kushalmahapatro** [comment]
Hi @erperejildo 
Sorry about that. I will have a look at this ASAP and will update it by tonight.

**Comment by erperejildo** [comment]
Hi @kushalmahapatro. Any updates on that error?
