### ISSUE TITLE
Bottom Navigation freezing in Flutter 3.22.0

### ISSUE THREAD

**Issue by chihuy105** [kushalmahapatro/cuberto_bottom_bar#20]
Some how the bottom bar is freezing in Flutter 3.22.0 can you have me check on it. It only hapens in release or profile mode when I build to TestFlight.
Thanks

**Comment by kushalmahapatro** [comment]
Hi @chihuy105 , 
By freeze, you mean that the tab index doesn't change?

And can you please let me know if you are using the latest version 3.1.0
https://pub.dev/packages/cuberto_bottom_bar/versions/3.1.0

There was a regression with Flutter 3.22.0 regarding key only in non debug builds which was addressed in the latest version.

**Comment by chihuy105** [comment]
Oh sorry the bug is coming from the auto_route package. Thanks for the quick reply.

**Comment by chihuy105** [comment]
No bug here. Thanks

**Comment by chihuy105** [comment]
Yep. I try the 3.1.0 and it's fixed. Many thanks for the quick rely.
