### ISSUE TITLE
Programmatically select tab

### ISSUE THREAD

**Issue by easysoft-mobility** [kushalmahapatro/cuberto_bottom_bar#7]
I would lite to thanks you for this beautiful bottom tab bar.

About my issue, the app I'm developping has somes buttons allowing to switch to others screens. And same behaviour is served by bottombar also but I need to keep all two widgets into the app (buttons and bottom bar) to ease the user experience.
So when users clics on button, we need bottom bar to update it's state and reflect actual screen.
So please help me by adding a way to programmatically select tab to reflect user screen change.

Thanks !

**Comment by kushalmahapatro** [comment]
Hi @easysoft-mobility , first of all, thanks for using this plugin. 

I would surely be delightful to help you with this. Can you please explain to me what exactly do you want in this as that I would be adding it and publishing the same ASAP.

**Comment by mojocrack** [comment]
> Hi @easysoft-mobility , first of all, thanks for using this plugin.
> 
> I would surely be delightful to help you with this. Can you please explain to me what exactly do you want in this as that I would be adding it and publishing the same ASAP.

Thanks for reply !!
In fact, my app has list of products at the home screen. These list are just a preview of each category of products. And a "See more" button is below each list. So when user click these buttons, another widget replace the current one looking like what we do with fragments in android programming.
My problem is that the same behaviour is available when user click somes tabs in bottom tab bar.

So when you use buttom bar, the tab icon and text change as normal and it's very fine but when you use the "see more" button which is below list, you navigate to new view but bottom bar tab does'nt update itself so tab's icon/text does'nt match the new screen as no interaction has been done with bottom bar. 

Then my request is to have a way to programatically call bottom bar tabs's update, so they can behave like user clicked on them.

This feature will be very important also for people who want to implement swipe left-right pagination. So when users swipe left or right to change page, we can replace page (view/widget) and update programmatically the bottom bar tab to match the new screen's icon/text.

Thanks !
> 

>

**Comment by easysoft-mobility** [comment]
> Hi @easysoft-mobility , first of all, thanks for using this plugin.
> 
> I would surely be delightful to help you with this. Can you please explain to me what exactly do you want in this as that I would be adding it and publishing the same ASAP.

Thanks for reply !!
In fact, my app has list of products at the home screen. These list are just a preview of each category of products. And a "See more" button is below each list. So when user click these buttons, another widget replace the current one looking like what we do with fragments in android programming.
My problem is that the same behaviour is available when user click somes tabs in bottom tab bar.

So when you use buttom bar, the tab icon and text change as normal and it's very fine but when you use the "see more" button which is below list, you navigate to new view but bottom bar tab does'nt update itself so tab's icon/text does'nt match the new screen as no interaction has been done with bottom bar.

Then my request is to have a way to programatically call bottom bar tabs's update, so they can behave like user clicked on them.

This feature will be very important also for people who want to implement swipe left-right pagination. So when users swipe left or right to change page, we can replace page (view/widget) and update programmatically the bottom bar tab to match the new screen's icon/text.

Thanks !

**Comment by kushalmahapatro** [comment]
Hi, @easysoft-mobility Thanks for this, got it, will surely implement this and give in the next release ASAP.

**Comment by kushalmahapatro** [comment]
HI, @easysoft-mobility , I have added the feature to programmatically change the tab. U have to replace the initialSelection key with selectedTab and provide the tab index of the tab to it. 

Please do have a look at the example and lemme know if anything else required.

**Comment by easysoft-mobility** [comment]
Hi kushal !
The  enhancement worked fine !
Thank a lot !
You made my app look great yeah
